### ISSUE TITLE
socsec fails to verify Mode2 AES option 1 encrypted BL1 image for A0

### ISSUE THREAD

**Issue by amboar** [AspeedTech-BMC/socsec#1]
```
+ coverage run -p ./socsec verify --soc 2600 --sec_image tests/data/generated/2600-a0_mode2aes1-rsa1024-sha224/bl1.signed.bin --output tests/data/generated/2600-a0_mode2aes1-rsa1024-sha224/bl1.bin --otp_image tests/data/generated/2600-a0_mode2aes1-rsa1024-sha224/otp-all.image
Algorithm: AES_RSA_SHA
RSA length: 1024
HASH length: 224
check RoT header PASS
Verify key ...
Key Type: OEM DSS public keys
ID: 0
M:
00000000: 81 92 08 C7 80 CF 64 23  FB 51 3C 47 E1 1D 69 A7  ......d#.Q<G..i.
00000010: 0A 5F C8 06 CB C7 40 10  86 A8 97 93 E9 31 08 E4  ._....@......1..
00000020: 95 63 58 56 FA C7 36 1F  95 4A 3A C2 B9 D8 25 7D  .cXV..6..J:...%}
00000030: E6 01 D0 23 56 49 69 4D  90 0D 49 4D F2 76 96 9C  ...#VIiM..IM.v..
00000040: AA 71 43 EC 0A 7B 0B 96  09 C8 CD 19 CC 1E 80 40  .qC..{.........@
00000050: 36 61 42 89 92 33 14 33  18 BD 68 CE 6F C8 66 46  6aB..3.3..h.o.fF
00000060: 5B 9A A1 04 1A 9F 67 2F  1B 33 D4 63 05 C4 9C B1  [.....g/.3.c....
00000070: 34 6A 22 25 F2 93 42 C6  7E 79 87 4D 41 59 C9 E2  4j"%..B.~y.MAY..
E:
00000000: 01 00 01                                          ...
Traceback (most recent call last):
  File "./socsec", line 1693, in <module>
    tool.run(sys.argv)
  File "./socsec", line 1649, in run
    args.func(args)
  File "./socsec", line 1683, in verify_secure_image
    self.verify.verify_secure_image(args.soc,
  File "./socsec", line 1450, in verify_secure_image
    dec_image = self.verify_rot_image(sec_image[:sign_image_size+1024],
  File "./socsec", line 1412, in verify_rot_image
    dec_image = self.mode2_decrypt(sec_image, sign_image_size,
  File "./socsec", line 1331, in mode2_decrypt
    M = int.from_bytes(key['M'], byteorder='little', signed=False)
KeyError: 'M'
```

It appears `socsec` assumes the A1 key header ABI, but the A0 ABI has a different enumeration values for the key types.

A0 support in `otptool`: https://github.com/AspeedTech-BMC/socsec/blob/v00.01.06/otptool.py#L393-L402

A1 support in `otptool`: https://github.com/AspeedTech-BMC/socsec/blob/v00.01.06/otptool.py#L435-L444

Key header decoding in `socsec`: https://github.com/AspeedTech-BMC/socsec/blob/v00.01.06/socsec.py#L1244

**Comment by amboar** [comment]
Fixed by the following:

```
From fb6a1fe31ff2171637e270924fdf1b25f250d11b Mon Sep 17 00:00:00 2001
From: Andrew Jeffery <andrew@aj.id.au>
Date: Wed, 16 Dec 2020 16:32:39 +1030
Subject: [PATCH] wip: socsec: Paper over A0 / A1 key header ABI
 incompatibilities

https://github.com/AspeedTech-BMC/socsec/issues/1

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
---
 socsec.py | 20 +++++++++++++++++---
 1 file changed, 17 insertions(+), 3 deletions(-)

diff --git a/socsec.py b/socsec.py
index 001b4e50a9c0..968bd8c3a7f5 100755
--- a/socsec.py
+++ b/socsec.py
@@ -1215,7 +1215,20 @@ class SecureBootVerify(object):
                          signature_num_bytes, public_key_num_bytes), \
             header_offset, retire_list
 
-    def parse_data(self, alg_data, data_region, retire_list):
+    def parse_data(self, info_struct, alg_data, data_region, retire_list):
+        if info_struct['version'] == 'A0':
+            type_lookup = { 0x0 : AES_OEM,
+                            0x1 : AES_VAULT,
+                            0x8 : RSA_OEM,
+                            0xa : RSA_SOC_PUB,
+                            0xe : RSA_SOC_PRI }
+        else:
+            type_lookup = { 0x1 : AES_VAULT,
+                            0x2 : AES_OEM,
+                            0x8 : RSA_OEM,
+                            0xa : RSA_SOC_PUB,
+                            0xe : RSA_SOC_PRI }
+
         key_list = []
         find_last = 0
         for i in range(16):
@@ -1224,7 +1237,7 @@ class SecureBootVerify(object):
             kl['ID'] = h & 0x7
             kl['RETIRE'] = retire_list[kl['ID']]
             kl['OFFSET'] = ((h >> 3) & 0x3ff) << 3
-            kl['TYPE'] = (h >> 14) & 0xf
+            kl['TYPE'] = type_lookup[(h >> 14) & 0xf]
             kl['PAR'] = (h >> 18) & 0x3
             key_list.append(kl)
             if h & (1 << 13):
@@ -1432,7 +1445,8 @@ class SecureBootVerify(object):
         alg_data, header_offset, retire_list = self.parse_config(soc_version,
                                                                  config_region)
 
-        key_list = self.parse_data(alg_data, data_region, retire_list)
+        key_list = self.parse_data(info_struct, alg_data, data_region,
+                                   retire_list)
         header = sec_image[header_offset:header_offset +
                            self.sec.ROT_HEADER_SIZE]
         (aes_data_offset, enc_offset, sign_image_size, signature_offset,
-- 
2.27.0
```
